[package]
name = "scribe"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
colored = "2.1.0"
homedir = "0.3.3"
rusqlite = { version = "0.32.0", features = ["bundled"] }
termion = "1.5.5"

